/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.GUI;

import modules.weather.WeatherEntry;
import javax.swing.*;
import java.awt.*;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
/**
 *
 * @author Nicolas
 */
public class WeatherCardPanel extends JPanel {

    /**
     * Creates new form WeatherCardPanel
     */
    public WeatherCardPanel(WeatherEntry entry) {
        setBorder(BorderFactory.createEtchedBorder());
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 10, 5, 10);
        gbc.anchor = GridBagConstraints.WEST;

        DateTimeFormatter dayFormatter = DateTimeFormatter.ofPattern("EEEE d", new Locale("es", "ES"));
        JLabel dateLabel = new JLabel(entry.getDate().format(dayFormatter));
        dateLabel.setFont(new Font("Segoe UI", Font.BOLD, 22));
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2; 
        add(dateLabel, gbc);

        JLabel conditionLabel = new JLabel(entry.getCondition());
        conditionLabel.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        gbc.gridy = 1;
        add(conditionLabel, gbc);

        JLabel maxTempLabel = new JLabel(String.format("Max: %.1f °C", entry.getMaxTemp()));
        maxTempLabel.setFont(new Font("Segoe UI", Font.BOLD, 16));
        gbc.gridy = 2;
        gbc.gridwidth = 1;
        add(maxTempLabel, gbc);

        JLabel minTempLabel = new JLabel(String.format("Min: %.1f °C", entry.getMinTemp()));
        minTempLabel.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        gbc.gridx = 1;
        add(minTempLabel, gbc);

        JLabel precipitationLabel = new JLabel(String.format("Precipitation: %.1f mm", entry.getPrecipitation()));
        precipitationLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        gbc.gridx = 0;
        gbc.gridy = 3;
        add(precipitationLabel, gbc);

        JLabel windLabel = new JLabel(String.format("WindSpeed: %.1f km/h", entry.getWindSpeed()));
        windLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        gbc.gridx = 1;
        add(windLabel, gbc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
